# Stack theme config for palladius.github.io
baseURL: "https://palladius.github.io"
paginate: 12
title: "Riccardo's 🐡 Blog"
defaultContentLanguage: "en"
enableRobotsTXT: true
summaryLength: 30

# Hugo module - Stack theme
module:
  imports:
    - path: "github.com/CaiJimmy/hugo-theme-stack/v4"
