# Stack theme params
mainSections:
  - "posts"

sidebar:
  emoji: "🐡"
  subtitle: "Italian in Zürich. SRE, AI, Ruby."

article:
  math: false
  readingTime: true
  toc: true

footer:
  since: 2005

colorScheme:
  toggle: true
  default: "auto"

widgets:
  homepage:
    - type: search
    - type: categories
    - type: tag-cloud
      params:
        limit: 20
