version: '3'

services:
  site:
    image: jekyll/jekyll:4.2.0
    command: jekyll serve --livereload --verbose
    ports:
      - 4000:4000
    volumes:
      - ./blog/:/srv/jekyll
      - ./blog/vendor/bundle:/usr/local/bundle